#version: '2'
# The following service only builds the image and does not run the container.
# run "docker-compose -f docker-compose-build-only.yml build"

#services:
#
#  composer:
#      image: composer
#      container_name: composer